
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import requests

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import json



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets_tampilDataKum")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

dataKumulatifs={}
import gui_DataKum
print(gui_DataKum.id_user)

class MainGUI(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self._frame = None
        self.switch_frame(tampilDataKum)
        self.title('Pendataan Kasus Covid-19 Indonesia')
        self.geometry("1000x600")
        self.configure(bg = "#FFFFFF")

    def switch_frame(self, frame_class):
        """Destroys current frame and replaces it with a new one."""
        new_frame = frame_class(self)
        if self._frame is not None:
            self._frame.destroy()
        self._frame = new_frame

class tampilDataKum(tk.Frame):
    def __init__(self,master):
        tk.Frame.__init__(self, master) 
        #window = Toplevel
        master.geometry("1000x600")
        master.title('Pendataan Kasus Covid-19 Indonesia')
        master.configure(bg = "#FFFFFF")
        #declaring variable for Login    

        canvas = Canvas(
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        date = requests.get("http://localhost:5000/kasus/date")
        
        def tampilKumulatif():
            import login
            url = "http://localhost:5000/kasus/user_id/" +str(gui_DataKum.id_user)
            date = requests.get("http://localhost:5000/kasus/date")
            myjson = {
                'tanggal': date.text
            }
            response = requests.get(url,json = myjson)
            return response.text

        global dataKumulatifs
        dataKumulatifs = tampilKumulatif()
        print(dataKumulatifs)
        x = requests.get("http://localhost:5000/users/"+str(gui_DataKum.id_user))
        meninggal = sum(map(lambda x: int(x['meninggal']), json.loads(dataKumulatifs)))
        sembuh = sum(map(lambda x: int(x['sembuh']), json.loads(dataKumulatifs)))
        positif = sum(map(lambda x: int(x['positif']), json.loads(dataKumulatifs)))
        kota = str(x.json()[0]['kota'])
        print(kota)
        
        canvas.place(x = 0, y = 0)
        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            750.0,
            385.0,
            image=entry_image_1
        )
        #sembuh
        entry_1 = canvas.create_text(
            616.0,
            368.0,
            anchor="nw",
            text=sembuh,
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            750.0,
            459.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0
        )
        entry_2 = canvas.create_text(
            616.0,
            440.0,
            anchor="nw",
            text=meninggal,
            fill="#000000",
            font=("Inter", 20 * -1)
        )
        

        canvas.create_text(
            609.0,
            341.0,
            anchor="nw",
            text="Sembuh",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        entry_bg_3 = canvas.create_image(
            751.0,
            311.0,
            image=entry_image_3
        )
        entry_3 = canvas.create_text(
            616.0,
            294.0,
            anchor="nw",
            text=positif,
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            610.0,
            267.0,
            anchor="nw",
            text="Kasus Positif",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        entry_bg_4 = canvas.create_image(
            750.0,
            237.0,
            image=entry_image_4
        )
        entry_4 = canvas.create_text(
            616.0,
            220.0,
            anchor="nw",
            text=date.text,
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            609.0,
            193.0,
            anchor="nw",
            text="Tanggal",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        entry_image_5 = PhotoImage(
            file=relative_to_assets("entry_5.png"))
        entry_bg_5 = canvas.create_image(
            750.0,
            164.0,
            image=entry_image_5
        )
        entry_5 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0
        )

        entry_5 = canvas.create_text(
            616.0,
            150.0,
            anchor="nw",
            text=kota,
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            609.0,
            120.0,
            anchor="nw",
            text="Kota",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            609.0,
            415.0,
            anchor="nw",
            text="Meninggal",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_rectangle(
            0.0,
            0.0,
            459.0,
            600.0,
            fill="#00D1FF",
            outline="")

        canvas.create_text(
            37.0,
            145.0,
            anchor="nw",
            text="Pendataan Kasus COVID-19\nIndonesia",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        canvas.create_text(
            37.0,
            77.0,
            anchor="nw",
            text="Data Kumulatif",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            229.0,
            414.0,
            image=image_image_1
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("homepage"),
            relief="flat"
        )
        button_1.place(
            x=37.0,
            y=8.0,
            width=102.0,
            height=37.0
        )

        master.resizable(False, False)
        master.mainloop()

if __name__ == "__main__":
    app = MainGUI()
    app.mainloop()
