
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Canvas, Entry, Text, Button, PhotoImage, StringVar, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets_Homepage")


def relative_to_assets_homepage(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class MainGUI(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self._frame = None
        self.switch_frame(Homepage)
        self.title('Pendataan Kasus Covid-19 Indonesia')
        self.geometry("1000x600")
        self.configure(bg = "#FFFFFF")

    def switch_frame(self, frame_class):
        """Destroys current frame and replaces it with a new one."""
        new_frame = frame_class(self)
        if self._frame is not None:
            self._frame.destroy()
        self._frame = new_frame


# Page Homepage
class Homepage(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master)
        master.geometry("1000x600")
        master.configure(bg = "#FFFFFF")
        master.title('Pendataan Kasus Covid-19 Indonesia')

        canvas = Canvas(
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1000.0,
            75.0,
            fill="#00D1FF",
            outline="")

        canvas.create_text(
            40.0,
            20.0,
            anchor="nw",
            text="Pendataan Kasus COVID-19 Indonesia",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        canvas.create_text(
            164.0,
            281.0,
            anchor="nw",
            text="Tambah Data",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            470.0,
            281.0,
            anchor="nw",
            text="Ubah Data",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            750.0,
            281.0,
            anchor="nw",
            text="Data Kumulatif",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            170.0,
            501.0,
            anchor="nw",
            text="Data Pilihan",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            479.0,
            501.0,
            anchor="nw",
            text="Bantuan",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            763.0,
            501.0,
            anchor="nw",
            text="Ubah Profil",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        #data Kumulatif
        button_image_1 = PhotoImage(
            file=relative_to_assets_homepage("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("dataKum"),
            relief="flat"
        )
        button_1.place(
            x=745.0,
            y=140.0,
            width=120.0,
            height=120.0
        )
        
        #Tambah Data
        button_image_2 = PhotoImage(
            file=relative_to_assets_homepage("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("tambahData"),
            relief="flat"
        )
        button_2.place(
            x=154.0,
            y=140.0,
            width=120.0,
            height=120.0
        )

        #data pilihan
        button_image_3 = PhotoImage(
            file=relative_to_assets_homepage("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("tampilDataPilihan"),
            relief="flat"
        )
        button_3.place(
            x=154.0,
            y=365.0,
            width=120.0,
            height=120.0
        )

        #ubah profil
        button_image_4 = PhotoImage(
            file=relative_to_assets_homepage("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("ubahProfil"),
            relief="flat"
        )
        button_4.place(
            x=745.0,
            y=365.0,
            width=120.0,
            height=120.0
        )

        #ubah data
        button_image_5 = PhotoImage(
            file=relative_to_assets_homepage("button_5.png"))
        button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("ubahData"),
            relief="flat"
        )
        button_5.place(
            x=450.0,
            y=140.0,
            width=120.0,
            height=120.0
        )

        #bantuan
        button_image_6 = PhotoImage(
            file=relative_to_assets_homepage("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        button_6.place(
            x=450.0,
            y=365.0,
            width=120.0,
            height=120.0
        )

        #logout
        button_image_7 = PhotoImage(
            file=relative_to_assets_homepage("button_7.png"))
        button_7 = Button(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame("login"),
            relief="flat"
        )
        button_7.place(
            x=874.0,
            y=18.0,
            width=102.0,
            height=37.0
        )
        master.resizable(False, False)
        master.mainloop()

if __name__ == "__main__":
    app = MainGUI()
    app.mainloop()
