
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets_login")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    736.0,
    171.9999999999999,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F4F4F4",
    highlightthickness=0
)
entry_1.place(
    x=602.0,
    y=151.9999999999999,
    width=268.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    736.0,
    245.9999999999999,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F4F4F4",
    highlightthickness=0
)
entry_2.place(
    x=602.0,
    y=225.9999999999999,
    width=268.0,
    height=38.0
)

canvas.create_text(
    595.0,
    127.99999999999989,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Inter", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=756.0,
    y=288.9999999999999,
    width=123.0,
    height=21.0
)

canvas.create_text(
    595.0,
    201.9999999999999,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    0.0,
    1.1368683772161603e-13,
    459.0,
    600.0000000000001,
    fill="#00D1FF",
    outline="")

canvas.create_text(
    28.0,
    127.99999999999989,
    anchor="nw",
    text="Pendataan Kasus COVID-19\nIndonesia",
    fill="#FFFFFF",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    595.0,
    349.9999999999999,
    anchor="nw",
    text="Belum punya akun? ",
    fill="#000000",
    font=("Inter", 17 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=765.0,
    y=349.9999999999999,
    width=79.0,
    height=21.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=595.0,
    y=281.9999999999999,
    width=93.0,
    height=32.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    229.0,
    413.9999999999999,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
