
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import requests

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Canvas, Entry, Text, Button, PhotoImage, StringVar, ttk



OUTPUT_PATH = Path(__file__).parent

ASSETS_PATH_LOGIN = OUTPUT_PATH / Path("./assets_login")
ASSETS_PATH_REGISTER = OUTPUT_PATH / Path("./assets_register")
ASSETS_PATH_HOMEPAGE = OUTPUT_PATH / Path("./assets_Homepage")

def relative_to_assets_homepage(path: str) -> Path:
    return ASSETS_PATH_HOMEPAGE / Path(path)

def relative_to_assets_login(path: str) -> Path:
    return ASSETS_PATH_LOGIN / Path(path)
    
def relative_to_assets_register(path: str) -> Path:
    return ASSETS_PATH_REGISTER / Path(path)



new_register = 0
accessToken = ""

class MainGUI(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self._frame = None
        self.switch_frame(Login)
        self.title('Pendataan Kasus Covid-19 Indonesia')
        self.geometry("1000x600")
        self.configure(bg = "#FFFFFF")
    
    # Fungsi Ganti Page
    def switch_frame(self, frame_class):
        """Destroys current frame and replaces it with a new one."""
        new_frame = frame_class(self)
        if self._frame is not None:
            self._frame.destroy()
        self._frame = new_frame

# Page Login
class Login(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master) 
        #window = Toplevel
        
        #declaring variable for Login
        global  message
        global username
        global password
        
        username = StringVar ()
        password = StringVar ()
        message= StringVar ()
        

        master.geometry("1000x600")
        master.title('Pendataan Kasus Covid-19 Indonesia')
        #window.configure(bg = "#FFFFFF")

        canvas = Canvas(
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        entry_image_1 = PhotoImage(
            file=relative_to_assets_login("entry_1.png"))
            
        entry_bg_1 = canvas.create_image(
            736.0,
            171.9999999999999,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0,
            textvariable= username
        )
        entry_1.place(
            x=602.0,
            y=151.9999999999999,
            width=268.0,
            height=38.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets_login("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            736.0,
            245.9999999999999,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0,
            textvariable= password
        )
        entry_2.place(
            x=602.0,
            y=225.9999999999999,
            width=268.0,
            height=38.0
        )

        canvas.create_text(
            595.0,
            127.99999999999989,
            anchor="nw",
            text="Username",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets_login("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=756.0,
            y=288.9999999999999,
            width=123.0,
            height=21.0
        )

        canvas.create_text(
            595.0,
            201.9999999999999,
            anchor="nw",
            text="Password",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_rectangle(
            0.0,
            1.1368683772161603e-13,
            459.0,
            600.0000000000001,
            fill="#00D1FF",
            outline="")

        canvas.create_text(
            28.0,
            127.99999999999989,
            anchor="nw",
            text="Pendataan Kasus COVID-19\nIndonesia",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        canvas.create_text(
            595.0,
            349.9999999999999,
            anchor="nw",
            text="Belum punya akun? ",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets_login("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: master.switch_frame(Register),
            relief="flat"
        )
        button_2.place(
            x=765.0,
            y=349.9999999999999,
            width=79.0,
            height=21.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets_login("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command= lambda:self.login(),
            relief="flat"
        )
        button_3.place(
            x=595.0,
            y=281.9999999999999,
            width=93.0,
            height=32.0
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets_login("image_1.png"))
        image_1 = canvas.create_image(
            229.0,
            413.9999999999999,
            image=image_image_1
        )
        
        errorlogin = canvas.create_text(
                            595.0,
                            329.9999999999999,
                            anchor="nw",
                            text='',
                            fill="#ff0000",
                            font=("Inter", 17 * -1)
        )
          
        # Muncul setelah Register akun baru
        if(new_register == 1):
            canvas.create_text(
                650.0,
                100.0,
                anchor="nw",
                text="Akun Baru Terdaftar!",
                fill="#000000",
                font=("Inter", 20 * -1)
            )
        master.resizable(False, False)
        master.mainloop()

    def login(self):
    #getting form data
        uname=username.get()
        pwd=password.get()
        global accessToken
        #applying empty validation
        try:
            if uname=='' or pwd=='':
                message.set("fill the empty field!!!")
        
            else:
                print(uname,pwd)
                url = 'http://localhost:5000/users/login'
                myjson = {
                    'email': uname,
                    'password':pwd
                    }
                x = requests.post(url, json = myjson)
                #print the response text (the content of the requested file):
                if x.status_code == 200:
                    #navigate to menu page
                    # print("here")
                    # url = 'http://localhost:5000/users/token'
                    # response_token = requests.get(url)
                    jsonToken = x.json()
                    accessToken = jsonToken["accessToken"]
                    print(accessToken)
                    self.master.switch_frame(Homepage)
                else:
                    self.entry_1.delete(0, 'end')
                    self.entry_2.delete(0, 'end')
                    jsonResponse = x.json()
                    self.canvas.itemconfig(self.errorlogin, text=jsonResponse["msg"])
                    print(x.text)
        except:
            self.entry_1.delete(0, 'end')
            self.entry_2.delete(0, 'end')
            self.canvas.itemconfig(self.errorlogin, text="Gagal Menghubungkan ke Server")

# Page Register
class Register(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master) 
        master.geometry("1000x600")
        master.title('Pendataan Kasus Covid-19 Indonesia')
        #window.configure(bg = "#FFFFFF")

        #declaring variable for Login
        global message
        global surel
        global password
        global confPassword
        global name

        surel = StringVar ()
        password = StringVar ()
        message= StringVar ()
        confPassword= StringVar ()
        name = StringVar()
        kota = StringVar

        canvas = Canvas(
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        entry_image_1 = PhotoImage(
            file=relative_to_assets_login("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            736.0,
            172.0,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0,
            textvariable=surel
        )
        entry_1.place(
            x=602.0,
            y=152.0,
            width=268.0,
            height=38.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets_register("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            736.0,
            246.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0,
            textvariable=password
        )
        entry_2.place(
            x=602.0,
            y=226.0,
            width=268.0,
            height=38.0
        )

        canvas.create_text(
            595.0,
            128.0,
            anchor="nw",
            text="Username",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_text(
            595.0,
            202.0,
            anchor="nw",
            text="Password",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        entry_image_3 = PhotoImage(
            file=relative_to_assets_register("entry_3.png"))
        entry_bg_3 = canvas.create_image(
            736.0,
            318.0,
            image=entry_image_3
        )
        entry_3 = Entry(
            bd=0,
            bg="#F4F4F4",
            highlightthickness=0,
            textvariable=confPassword
        )
        entry_3.place(
            x=602.0,
            y=298.0,
            width=268.0,
            height=38.0
        )

        canvas.create_text(
        595.0,
        274.0,
        anchor="nw",
        text="Konfirmasi Password",
        fill="#000000",
        font=("Inter", 20 * -1)
        )

        canvas.create_text(
        595.0,
        346.0,
        anchor="nw",
        text="Kota",
        fill="#000000",
        font=("Inter", 18 * -1)
        )

        n = StringVar()
        self.kotaTerpilih = ttk.Combobox(master, width = 27,state="readonly", 
                                    textvariable = n,font=("Inter", 12 * -1))
        
        # Adding combobox drop down list
        self.kotaTerpilih['values'] = (' Jakarta', 
                                ' Tangerang',
                                ' Depok',
                                ' Bekasi',
                                ' Bogor',
                                ' Palembang', 
                                )

        self.kotaTerpilih.bind("<<ComboboxSelected>>",lambda e: master.focus())
        
        self.kotaTerpilih.place(
            x=602.0,
            y=372.0,
            width=268.0,
            height=38.0
        )
        canvas.create_rectangle(
            0.0,
            0.0,
            459.0,
            600.0,
            fill="#00D1FF",
            outline="")

        canvas.create_text(
            28.0,
            128.0,
            anchor="nw",
            text="Pendataan Kasus COVID-19\nIndonesia",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        canvas.create_text(
            595.0,
            490.0,
            anchor="nw",
            text="Sudah punya akun? ",
            fill="#000000",
            font=("Inter", 17 * -1)
        )

        errorregis = canvas.create_text(
            595.0,
            480.0,
            anchor="nw",
            text="",
            fill="#ff0000",
            font=("Inter", 12 * -1)
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets_register("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.new_regist(),
            relief="flat"
        )
        button_1.place(
            x=768.0,
            y=490.0,
            width=52.0,
            height=25.0
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets_register("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.register(),
            relief="flat"
        )
        button_2.place(
            x=631.0,
            y=429.0,
            width=209.0,
            height=38.0
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets_register("image_1.png"))
        image_1 = canvas.create_image(
            238.0,
            427.0,
            image=image_image_1
        )
        
        #if(new_register == 1):
        #    master.switch_frame(Login)
        
        master.resizable(False, False)
        master.mainloop()
        
    def new_regist(self):
        self.master.switch_frame(Login)

    def register(self):
        global new_register
        new_register = 1
        uname=surel.get()
        name="arif"
        pwd=password.get()
        kota= str(self.kotaTerpilih.get())
        print(kota)
        # self.master.switch_frame(Login)
        #applying empty validation
        try:
            if uname=='' or pwd=='':
                message.set("fill the empty field!!!")
                self.canvas.itemconfig(self.errorregis, text=message)
            else:
                print(uname,pwd)
                url = 'http://localhost:5000/users'
                myjson = {
                    'name':name,
                    'email': uname,
                    'password':pwd,
                    'confPassword':confPassword,
                    'kota': kota
                    }
                x = requests.post(url, json = myjson)
                print(x.status_code)
                self.master.switch_frame(Login)
                # #print the response text (the content of the requested file):
                # if x.status_code == 200:
                #     self.master.switch_frame(Login)
                # else:
                #     self.entry_1.delete(0, 'end')
                #     self.entry_2.delete(0, 'end')
                #     jsonResponse = x.json()
                #     self.canvas.itemconfig(self.errorregis, text=jsonResponse["msg"])
                #     print(x.text)
        except:
            self.entry_1.delete(0, 'end')
            self.entry_2.delete(0, 'end')
            self.canvas.itemconfig(self.errorregis, text="Gagal Menghubungkan ke Server")
    

# Page Homepage
class Homepage(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master)
        master.geometry("1000x600")
        master.configure(bg = "#FFFFFF")
        master.title('Pendataan Kasus Covid-19 Indonesia')

        global  refreshToken
        refreshToken = StringVar ()

        canvas = Canvas(
            bg = "#FFFFFF",
            height = 600,
            width = 1000,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1000.0,
            75.0,
            fill="#00D1FF",
            outline="")

        canvas.create_text(
            40.0,
            20.0,
            anchor="nw",
            text="Pendataan Kasus COVID-19 Indonesia",
            fill="#FFFFFF",
            font=("Inter SemiBold", 30 * -1)
        )

        canvas.create_text(
            164.0,
            281.0,
            anchor="nw",
            text="Tambah Data",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            470.0,
            281.0,
            anchor="nw",
            text="Ubah Data",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            750.0,
            281.0,
            anchor="nw",
            text="Data Kumulatif",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            170.0,
            501.0,
            anchor="nw",
            text="Data Pilihan",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            479.0,
            501.0,
            anchor="nw",
            text="Bantuan",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        canvas.create_text(
            763.0,
            501.0,
            anchor="nw",
            text="Ubah Profil",
            fill="#000000",
            font=("Inter Light", 16 * -1)
        )

        #datakumulatif
        button_image_1 = PhotoImage(
            file=relative_to_assets_homepage("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.datakumulatif(),
            relief="flat"
        )
        button_1.place(
            x=745.0,
            y=140.0,
            width=120.0,
            height=120.0
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets_homepage("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=154.0,
            y=140.0,
            width=120.0,
            height=120.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets_homepage("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        button_3.place(
            x=154.0,
            y=365.0,
            width=120.0,
            height=120.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets_homepage("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        button_4.place(
            x=745.0,
            y=365.0,
            width=120.0,
            height=120.0
        )

        button_image_5 = PhotoImage(
            file=relative_to_assets_homepage("button_5.png"))
        button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_5 clicked"),
            relief="flat"
        )
        button_5.place(
            x=450.0,
            y=140.0,
            width=120.0,
            height=120.0
        )

        button_image_6 = PhotoImage(
            file=relative_to_assets_homepage("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        button_6.place(
            x=450.0,
            y=365.0,
            width=120.0,
            height=120.0
        )
        master.resizable(False, False)
        master.mainloop()

        
    def datakumulatif(self):
        url = 'http://localhost:5000/kasus'
        global accessToken
        headers = {"Authorization":"Bearer " + accessToken}
        response = requests.get(url,headers=headers)
        data_json = response.json()
        print(data_json)
        # print(header)
            

if __name__ == "__main__":
    app = MainGUI()
    app.mainloop()